import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import * as c from '../scripts/core.ts';
import {selectModel} from '../scripts/routing.ts';
async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-activity-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=await c.start(dir,{id:'activity',host:{kind:'codex',model:'gpt-6-astra'},intent:'Synthetic subprocess ownership fixture',criteria:['Ownership gates actual overlap']});await c.plan(store,{tasks:['a','b'].map(id=>({id,title:id,goal:id,phase:'x',deps:[],resources:[id],criteria:['pass'],kind:'code',checks:[{id:'wait',command:process.execPath,args:['-e',"setTimeout(()=>{},600)"]}]})),integrationChecks:[]});for(const id of ['a','b']){const workspace=join(dir,id);await mkdir(workspace);await c.claim(store,id,{workspace,model:'gpt-6-astra'});await c.result(store,id,{});}return {dir,store};}
async function live(store:c.Store,id:string){for(let i=0;i<100;i++){const t=c.taskOf(await store.load(),id);if(t.activity&&t.activity.owner.pid!==process.pid)return t.activity;await new Promise(r=>setTimeout(r,10));}throw Error('No spawned activity');}
test('real check lease blocks duplicates, capacity and routing before gateway calls, then releases',async t=>{const {store}=await fixture(t);await store.transaction(s=>{s.config.maxWorkers=1;});const running=c.check(store,'a','wait');const activity=await live(store,'a');assert.equal(activity.kind,'check');assert.notEqual(activity.owner.pid,process.pid);assert.equal(c.activeTasks(await store.load()).length,1);const snapshot=await c.next(store);assert.equal(snapshot.action,'await-verification');assert.equal(snapshot.parallel?.available,0);assert.equal(snapshot.parallel?.running[0].kind,'check');assert.equal(snapshot.parallel?.independent.length,0);await assert.rejects(()=>c.check(store,'a','wait'),/already active/);await assert.rejects(()=>c.check(store,'b','wait'),/capacity/);let calls=0;const s=await store.load();const route=await selectModel(store,'a','reviewer',s.tasks[0].workspace!,{},(async()=>{calls++;throw Error('Must not call gateway');}) as typeof fetch);assert.equal(route.action,'dispatch-blocked');assert.equal(calls,0);await assert.rejects(()=>c.repair(store,'a'),/active/);await assert.rejects(()=>store.transaction(s=>c.invalidateTree(s,'a','Concurrent operation')),/running/);await running;assert.equal(c.activeTasks(await store.load()).length,0);assert.equal((await c.check(store,'b','wait')).code,0);});
test('independent checks overlap and resource-sharing checks stay serialized',async t=>{const {store}=await fixture(t);const a=c.check(store,'a','wait');await live(store,'a');const b=c.check(store,'b','wait');await live(store,'b');assert.equal(c.activeTasks(await store.load()).length,2);await Promise.all([a,b]);await store.transaction(s=>{s.tasks[1].resources=['a'];});const again=c.check(store,'a','wait');await live(store,'a');await assert.rejects(()=>c.check(store,'b','wait'),/Conflicting/);await again;});
test('failed check process clears its activity and retains failing receipt',async t=>{const {store,dir}=await fixture(t);await store.transaction(s=>{s.tasks[0].checks[0].command=join(dir,'missing-process');});assert.equal((await c.check(store,'a','wait')).code,1);assert.equal(c.taskOf(await store.load(),'a').activity,undefined);await c.repair(store,'a');});
test('resume preserves living verification and blocks interrupted verification',async t=>{const {store}=await fixture(t);const check=c.check(store,'a','wait');const activity=await live(store,'a');await c.resume(store);assert.equal(c.taskOf(await store.load(),'a').activity?.owner.operation,activity.owner.operation);await check;await store.transaction(s=>{s.tasks[0].activity={kind:'check',owner:{...activity.owner,pid:2147483647,coordinatorPid:process.pid}};});await c.resume(store);assert.ok(c.taskOf(await store.load(),'a').activity);await store.transaction(s=>{s.tasks[0].activity={kind:'check',owner:{...activity.owner,pid:2147483647,coordinatorPid:undefined}};});await c.resume(store);assert.equal(c.taskOf(await store.load(),'a').status,'blocked');assert.equal(c.taskOf(await store.load(),'a').activity,undefined);});
