import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile, readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { piRun, requestJson } from '../scripts/adapters.ts';
import { diagnostics, trace } from '../scripts/telemetry.ts';
import { main } from '../scripts/cli.ts';

async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-adapter-'));t.after(()=>rm(dir,{recursive:true,force:true}));const old={key:process.env.OPENROUTER_API_KEY,pi:process.env.AMALE_PI_ENTRY,node:process.env.AMALE_NODE};process.env.OPENROUTER_API_KEY='sk-or-fake-diagnostic-secret-12345';t.after(()=>{for(const [name,value] of [['OPENROUTER_API_KEY',old.key],['AMALE_PI_ENTRY',old.pi],['AMALE_NODE',old.node]])if(value===undefined)delete process.env[name!];else process.env[name!]=value;});return dir;}
const assistant={type:'message_end',message:{role:'assistant',model:'test/model',content:[{type:'text',text:'Completed fixture'}],stopReason:'stop',usage:{input:10,output:3,cost:{total:.001}}}};
async function piFixture(t:any,source:string){const dir=await fixture(t),entry=join(dir,'fake-pi.ts');await writeFile(entry,source);process.env.AMALE_PI_ENTRY=entry;process.env.AMALE_NODE=process.execPath;return {dir,input:{workspace:dir,model:'test/model',prompt:'fixture',sessionDir:join(dir,'.sessions'),diagnosticRoot:join(dir,'.diagnostics')}};}
const output=(items:unknown[])=>`process.stdout.write(${JSON.stringify(items.map(i=>JSON.stringify(i)).join('\n'))});`;

test('OpenRouter terminal status errors retain diagnostics without leaking credentials',async t=>{const dir=await fixture(t);for(const status of [400,401,402,403]){let calls=0;await assert.rejects(()=>requestJson('https://openrouter.ai/api/alpha/decisions',{},(async()=>{calls++;return new Response('{}',{status});}) as typeof fetch,dir),new RegExp(String(status)));assert.equal(calls,1);}const report=await diagnostics(dir);assert.equal(report.totals.failures,4);assert.ok(!JSON.stringify(report).includes(process.env.OPENROUTER_API_KEY!));});
test('retry status and usage are retained on eventual API success',async t=>{const dir=await fixture(t);let calls=0;const value=await requestJson('https://openrouter.ai/api/alpha/decisions',{},(async()=>++calls===1?new Response('{}',{status:429,headers:{'retry-after':'0.001'}}):Response.json({model:'jev',usage:{input_tokens:12,output_tokens:2,cost:.0001}})) as typeof fetch,dir);assert.equal(value.model,'jev');assert.equal(calls,2);const d=await diagnostics(dir);assert.equal(d.totals.inputTokens,12);assert.equal(d.totals.reportedCost,.0001);assert.equal(d.operations[0].events.filter((e:any)=>e.stage==='attempt').length,2);});
test('transport exhaustion and malformed success JSON are diagnosed',async t=>{const dir=await fixture(t);let calls=0;await assert.rejects(()=>requestJson('https://openrouter.ai/api/alpha/decisions',{},(async()=>{calls++;throw new Error('network '+process.env.OPENROUTER_API_KEY);}) as typeof fetch,dir),/bounded retries/);assert.equal(calls,3);await assert.rejects(()=>requestJson('https://openrouter.ai/api/alpha/decisions',{},(async()=>new Response('not JSON',{status:200})) as typeof fetch,dir));const report=await diagnostics(dir);assert.equal(report.totals.failures,2);assert.ok(!JSON.stringify(report).includes(process.env.OPENROUTER_API_KEY!));});
test('pi parses a final JSONL record without newline and records usage',async t=>{const {input}=await piFixture(t,output([assistant,{type:'agent_end'}]));const result=await piRun(input);assert.equal(result.text,'Completed fixture');const d=await diagnostics(input.diagnosticRoot);assert.equal(d.totals.inputTokens,10);assert.equal(d.totals.outputTokens,3);assert.equal(d.totals.estimatedCost,.001);assert.equal(d.totals.reportedCost,0);assert.equal(d.operations[0].outcome,'success');});
test('pi rejects incomplete, malformed, mismatched and failed response streams',async t=>{for(const [label,source] of [
 ['incomplete',output([assistant])],
 ['content-shape',output([{...assistant,message:{...assistant.message,content:{}}},{type:'agent_end'}])],
 ['content-null',output([{...assistant,message:{...assistant.message,content:[null]}},{type:'agent_end'}])],
 ['malformed',output([assistant,{type:'agent_end'}])+"process.stdout.write('\\ninvalid');"],
 ['model',output([{...assistant,message:{...assistant.message,model:'other/model'}},{type:'agent_end'}])],
 ['provider',output([{...assistant,message:{...assistant.message,stopReason:'error',errorMessage:'bad request'}},{type:'agent_end'}])]
]){await t.test(label,async st=>{const {input}=await piFixture(st,source);await assert.rejects(()=>piRun(input));assert.equal((await diagnostics(input.diagnosticRoot)).totals.failures,1);});}});
test('pi rejects spawn and ownership failures without leaving promises unresolved',async t=>{const {dir,input}=await piFixture(t,`setTimeout(()=>{},10000);`);process.env.AMALE_NODE=join(dir,'missing-node');await assert.rejects(()=>piRun(input),{code:"ENOENT"});const failed=await diagnostics(input.diagnosticRoot);assert.equal(failed.totals.failures,1);assert.equal(failed.totals.unfinished,0);assert.equal(failed.operations[0].events.at(-1)?.stage,"finished");process.env.AMALE_NODE=process.execPath;await assert.rejects(()=>piRun({...input,onSpawn:async()=>{throw new Error('owner checkpoint failed');}}),/owner checkpoint/);});
test('failed CLI initialization remains diagnosable without a valid run snapshot',async t=>{const dir=await fixture(t),request=join(dir,'request.json');await writeFile(request,'{}');await assert.rejects(()=>main(['start',dir,'failed',request]));const report=await main(['diagnose',dir,'failed']) as any;assert.ok(report.stateError);assert.equal(report.diagnostics.totals.failures,1);});
test('unfinished traces remain visible after a simulated interrupted operation',async t=>{const dir=await fixture(t);await trace(dir,'interrupted',{task:'x'});const report=await diagnostics(dir);assert.equal(report.totals.unfinished,1);assert.match(report.operations[0].outcome,/active or interrupted/);});
