import {clearCut} from './execution-fixture.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as c from '../scripts/core.ts';
import * as e from '../scripts/effort.ts';
async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-effort-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=await c.start(dir,{shape:clearCut,id:'effort',host:{kind:'codex',model:'gpt-6-astra'},intent:'Resolve architecture',criteria:['supported contract']});await e.configureEffort(store,{base:'medium',current:'medium',levels:['low','medium','high'],modes:['same-model-pass','session'],evidence:'Verified fixture capabilities'});return {dir,store};}
async function select(store:c.Store,choice='high'){await store.transaction(s=>s.decisions.push({id:'effort-1',question:'What effort?',criteria:{medium:'sufficient',high:'unresolved architecture needs deeper reasoning'},state:{hostModel:s.host.model,baseEffort:'medium'},revision:s.revision,choice,source:'jev-test'}));await e.requestEffort(store,{decisionId:'effort-1',purpose:'Resolve actual conflicting contract',reason:'Two consumers require incompatible shapes'});}
test('same model increases effort for a bounded pass then returns to baseline',async t=>{const {store}=await fixture(t);await select(store);assert.equal((await c.next(store)).action,'execute-host-effort');assert.equal((await store.load()).effort!.current,'medium');await e.startedEffort(store,{execution:'agent-1',model:'gpt-6-astra',level:'high',mode:'same-model-pass',evidence:'native dispatch receipt'});assert.equal((await c.next(store)).action,'await-host-effort');const artifact=await store.artifact({contract:'supported conclusion'});await e.finishedEffort(store,{execution:'agent-1',artifact,restoredEffort:'medium',evidence:'result received; coordinator unchanged'});assert.equal((await c.next(store)).action,'discover-specify-plan');assert.equal((await store.load()).host.model,'gpt-6-astra');await assert.rejects(()=>e.requestEffort(store,{decisionId:'effort-1',purpose:'again',reason:'again'}),/already consumed/);});
test('baseline choice avoids an unnecessary high effort pass',async t=>{const {store}=await fixture(t);await select(store,'medium');assert.equal((await store.load()).effort!.request,undefined);assert.equal((await c.next(store)).action,'discover-specify-plan');});
test('cannot substitute another model or invent an unsupported effort',async t=>{const {store}=await fixture(t);await select(store);for(const bad of [{model:'claude-fable',level:'high'},{model:'gpt-6-astra',level:'max'}])await assert.rejects(()=>e.startedEffort(store,{execution:'1',mode:'same-model-pass',evidence:'receipt',...bad}));await assert.rejects(()=>c.finish(store,['claim']),/effort pass/);});
test('pending effort survives resume and blocks an unsafe host switch',async t=>{const {store}=await fixture(t);await select(store);await c.resume(store);assert.equal((await c.next(store)).action,'execute-host-effort');await assert.rejects(()=>c.resume(store,{kind:'claude',model:'fable'}),/Reconcile active effort/);});
test('session escalation cannot finish without confirmed restoration and artifact',async t=>{const {store}=await fixture(t);await select(store);await e.startedEffort(store,{execution:'session-1',model:'gpt-6-astra',level:'high',mode:'session',evidence:'verified setting'});assert.equal((await store.load()).effort!.current,'high');const artifact=await store.artifact('result');await assert.rejects(()=>e.finishedEffort(store,{execution:'session-1',artifact,restoredEffort:'high',evidence:'not restored'}),/baseline/);await e.finishedEffort(store,{execution:'session-1',artifact,restoredEffort:'medium',evidence:'verified restored setting'});assert.equal((await store.load()).effort!.current,'medium');});
test('an effort request that cannot launch can reconcile without a fake execution',async t=>{const {store}=await fixture(t);await select(store);await e.reconcileEffort(store,{outcome:'not-started',restoredEffort:'medium',evidence:'Native adapter refused launch, no session created'});assert.equal((await store.load()).effort!.request,undefined);await c.resume(store,{kind:'claude',model:'fable'});assert.equal((await store.load()).host.model,'fable');assert.ok((await store.load()).events.some(e=>e.type==='effort-reconciled'));});
test('failed running effort needs exact execution and baseline restoration',async t=>{const {store}=await fixture(t);await select(store);await e.startedEffort(store,{execution:'failed-agent',model:'gpt-6-astra',level:'high',mode:'same-model-pass',evidence:'launch receipt'});await assert.rejects(()=>e.reconcileEffort(store,{outcome:'not-started',restoredEffort:'medium',evidence:'wrong'}));await e.reconcileEffort(store,{outcome:'failed',execution:'failed-agent',restoredEffort:'medium',evidence:'Execution terminated; coordinator unchanged'});assert.equal((await store.load()).effort!.request,undefined);});
