import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../scripts/core.ts';
import {recordHostAction,hostActions,exportDiagnostics} from '../scripts/host-diagnostics.ts';
import {trace} from '../scripts/telemetry.ts';
import {main} from '../scripts/cli.ts';
async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-host-ledger-'));t.after(()=>rm(dir,{recursive:true,force:true}));return {dir,store:new Store(dir,'run')};}
const observation={actionId:'private-action',sessionId:'private-session',kind:'review' as const,phase:'planned' as const,summary:'private project scope',next:'private next step'};
test('host evidence survives absent run state and a fresh Store with concurrent writes',async t=>{const {dir,store}=await fixture(t);await recordHostAction(store,observation);await Promise.all(['permission-denied','skipped'].map(phase=>recordHostAction(store,{...observation,phase:phase as any})));const ledger=await hostActions(new Store(dir,'run'));assert.equal(ledger.records.length,3);assert.ok(ledger.records.every(r=>r.source==='host-reported'));const report=await main(['diagnose',dir,'run']) as any;assert.ok(report.stateError);assert.equal(report.hostActions.records.length,3);});
test('invalid action is rejected; malformed local ledger does not hide healthy records',async t=>{const {store}=await fixture(t);await assert.rejects(()=>recordHostAction(store,{...observation,phase:'approved-forever' as any}));await recordHostAction(store,observation);await writeFile(join(store.root,'host-actions','deadbeef.json'),'{');const ledger=await hostActions(store);assert.equal(ledger.unreadable.length,1);assert.equal(ledger.records.length,1);});
test('structural export excludes unknown secrets and source identifiers without relying on secret registration',async t=>{const {dir,store}=await fixture(t);await recordHostAction(store,{...observation,summary:'arbitrary-unknown-secret C:/private/source.ts',next:'private-next'});const tr=await trace(store.root,'private-operation',{prompt:'private-prompt'});await tr.end('failed',{message:'private-error'});const result=await exportDiagnostics(new Store(dir,'run'));const text=JSON.stringify(result.bundle);for(const value of ['private-action','private-session','arbitrary-unknown-secret','C:/private','private-next','private-operation','private-prompt','private-error',dir])assert.ok(!text.includes(value),value);assert.equal(result.bundle.hostActions[0].action,'action-1');assert.equal(result.bundle.hostActions[0].phase,'planned');assert.equal(result.bundle.operations[0].outcome,'failed');assert.equal(result.bundle.state.available,false);});
test('CLI host-action and export work without initialized task state',async t=>{const {dir}=await fixture(t);const path=join(dir,'input.json');await writeFile(path,JSON.stringify(observation));await main(['host-action',dir,'run',path]);const result=await main(['diagnostic-export',dir,'run']) as any;assert.equal(result.bundle.hostActions.length,1);assert.ok(result.path.endsWith('.json'));});
