// Explicit opt-in integration probe. Never run as part of the ordinary test suite.
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { worker, reviewer, decide } from '../scripts/adapters.ts';
import * as c from '../scripts/core.ts';
const dir=resolve(process.argv[2]??'.amale-live');await mkdir(dir,{recursive:true});
await writeFile(join(dir,'charge.js'),'export const total = (price, quantity) => price + quantity;\n');
await writeFile(join(dir,'charge.test.js'),"import {total} from './charge.js'; if(total(10,2)!==20) throw new Error('Expected 20'); if(total(5,1)!==5) throw new Error('Expected 5');\n");
const store=await c.start(dir,{id:'billing-probe',host:{kind:'codex',model:'gpt-6-astra'},intent:'Fix total to multiply unit price by quantity',criteria:['total(10,2) equals 20 and total(5,1) equals 5']});
await c.plan(store,{tasks:[{id:'fix',title:'Correct total',goal:'Multiply unit price by quantity; no other behavior',phase:'fix',deps:[],resources:['charge'],criteria:['10 * 2 = 20; 5 * 1 = 5'],checks:[{id:'charge-test',command:process.execPath,args:['charge.test.js']}],kind:'code'} as c.TaskInput],integrationChecks:[{id:'all',command:process.execPath,args:['charge.test.js']}]});
const decision=await decide(store,{id:'route',question:'Which route is appropriate for this small known multiplication bug?',criteria:{execute:'Implement the given known fix',interview:'Missing user intent requires questions'},state:{intent:'total should multiply unit price by quantity',examples:['10*2=20','5*1=5']}});c.invariant(decision.choice==='execute','Probe requires host fallback before execution');
console.log(JSON.stringify({stage:'worker',routing:'automatic'}));const work=await worker(store,'fix',{workspace:dir,brief:'Fix charge.js only: multiply price by quantity. Do not edit tests or add files. Read the test, fix the function, run the test and report.'});c.invariant(!('action' in work),'Routing needs host action: '+JSON.stringify(work));
await c.check(store,'fix','charge-test');console.log(JSON.stringify({stage:'reviewer',routing:'automatic'}));const inspection=await reviewer(store,'fix',undefined,['Spec','Standards','money expected amounts']);c.invariant(!('action' in inspection),'Review routing needs host action: '+JSON.stringify(inspection));await c.accept(store,'fix');await c.integrated(store,'fix','Direct isolated probe workspace, inspected expected amount contract');await c.check(store,undefined,'all');await c.finish(store,['Live pi worker fix and independent reviewer; deterministic amount checks passed']);console.log(JSON.stringify({stage:'complete',next:await c.next(store),routes:(await store.load()).events.filter(e=>e.type==='route-used').map(e=>e.detail)}));
