import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../scripts/core.ts';
import {preflight} from '../scripts/preflight.ts';
import {main} from '../scripts/cli.ts';
async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-preflight-'));t.after(()=>rm(dir,{recursive:true,force:true}));const prior=process.env.OPENROUTER_API_KEY;process.env.OPENROUTER_API_KEY='sk-or-synthetic-preflight-12345';t.after(()=>{if(prior===undefined)delete process.env.OPENROUTER_API_KEY;else process.env.OPENROUTER_API_KEY=prior;});return {dir,store:new Store(dir,'probe')};}
const input={network:'allowed' as const,channel:'synthetic-test'};
const response=()=>Response.json({model:'synthetic/jev',answers:{selection:{type:'choice',choice:'a',confidence:1,probabilities:{a:1,b:0}}}});
test('known restricted host makes zero requests and CLI persists permission-needed result',async t=>{const {dir,store}=await fixture(t);let calls=0;const result=await preflight(store,{...input,network:'restricted'},(async()=>{calls++;throw Error('must not fetch');}) as typeof fetch);assert.equal(calls,0);assert.equal(result.ready,false);assert.equal(result.action,'network-permission-needed');const path=join(dir,'input.json');await writeFile(path,JSON.stringify({...input,network:'restricted'}));assert.equal((await main(['preflight',dir,'probe',path]) as any).action,'network-permission-needed');});
test('preflight sends only synthetic state, validates choice, and cannot confer export authorization',async t=>{const {store}=await fixture(t);let calls=0;const result=await preflight(store,input,(async(url,init)=>{calls++;assert.equal(url,'https://openrouter.ai/api/alpha/decisions');const payload=JSON.parse(String(init?.body));assert.deepEqual(payload.state,{synthetic:true,options:{a:1,b:9}});return response();}) as typeof fetch);assert.equal(calls,1);assert.equal(result.ready,true);assert.equal(result.projectExportAuthorized,false);assert.equal(result.model,'synthetic/jev');assert.ok(!(await store.readArtifact(result.artifact)).includes(process.env.OPENROUTER_API_KEY!));});
test('one-shot transport failure is not misreported as a known sandbox denial',async t=>{const {store}=await fixture(t);let calls=0;const result=await preflight(store,{...input,network:'unknown'},(async()=>{calls++;throw Error('offline');}) as typeof fetch);assert.equal(calls,1);assert.equal(result.action,'network-unreachable');assert.equal(result.ready,false);});
test('authentication, credit, provider and malformed Jev failures are distinct',async t=>{const {store}=await fixture(t);for(const [status,action] of [[401,'credentials-needed'],[402,'credits-needed'],[403,'provider-access-denied'],[429,'provider-unavailable'],[500,'provider-unavailable']] as const){let calls=0;const result=await preflight(store,input,(async()=>{calls++;return new Response('{}',{status});}) as typeof fetch);assert.equal(calls,1);assert.equal(result.action,action);}const bad=await preflight(store,input,(async()=>Response.json({answers:{}})) as typeof fetch);assert.equal(bad.action,'jev-protocol-error');assert.equal(bad.ready,false);});

test('uncertain or wrong synthetic choice cannot mark the channel ready',async t=>{const {store}=await fixture(t);for(const [choice,confidence,probabilities] of [['a',.5,{a:.5,b:.5}],['b',1,{a:0,b:1}]] as const){const result=await preflight(store,input,(async()=>Response.json({model:'synthetic/jev',answers:{selection:{type:'choice',choice,confidence,probabilities}}})) as typeof fetch);assert.equal(result.ready,false);assert.equal(result.action,'jev-verification-needed');}});
