import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as c from '../scripts/core.ts';
import { choiceAnswer, hostDecision } from '../scripts/adapters.ts';
import { install, statusHtml } from '../scripts/cli.ts';

async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amale-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));await writeFile(join(dir,'app.txt'),'original');const store=await c.start(dir,{id:'run',host:{kind:'codex',model:'gpt-6-astra'},intent:'Correct charge amount',criteria:['Correct amount charged']});return {dir,store};}
const task=(id:string,deps:string[]=[])=>({id,title:id,goal:'Correct observable behavior',phase:'checkout',deps,resources:[id],criteria:['correct result'],kind:'code' as const,checks:[{id:'test',command:process.execPath,args:['-e','process.exit(0)']}]} as c.Task);
async function syntheticCoverage(store:c.Store,id:string){const state=await store.load();return c.reviewObligations(state,c.taskOf(state,id)).map(o=>({id:o.id,status:'covered' as const,evidence:'Synthetic protocol fixture only; not a real model review'}));}
async function deliver(store:c.Store,dir:string,id='a') {await c.claim(store,id,{workspace:dir,model:'deepseek/flash'});await c.result(store,id,{changed:'app.txt'});await c.check(store,id,'test');await c.review(store,id,{coverage:await syntheticCoverage(store,id),model:'z-ai/glm-flash',findings:[],fingerprint:await c.fingerprint(dir),report:'Spec and Standards inspected actual implementation'});await c.accept(store,id);await c.integrated(store,id,'Inspected integrated behavior and actual diff');}

test('small work completes with current checks and independent review',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[{id:'all',command:process.execPath,args:['-e','process.exit(0)']}]});assert.equal((await c.next(store)).action,'route-dispatch');await deliver(store,dir);await c.check(store,undefined,'all');await c.finish(store,['Checked exact expected amount']);assert.equal((await c.next(store)).action,'done');await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'x'}),/immutable/);});
test('rejects invalid graph identities and dependencies',async t=>{const {store}=await fixture(t);for(const tasks of [[task('a'),task('a')],[task('a',['missing'])],[task('a',['b']),task('b',['a'])]])await assert.rejects(()=>c.plan(store,{tasks,integrationChecks:[]}));});
test('failed or stale checks cannot be accepted',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});await c.review(store,'a',{coverage:await syntheticCoverage(store,'a'),model:'glm',fingerprint:await c.fingerprint(dir),findings:[],report:'inspected'});await assert.rejects(()=>c.accept(store,'a'),/checks/);await c.check(store,'a','test');await writeFile(join(dir,'app.txt'),'changed');await assert.rejects(()=>c.accept(store,'a'),/stale/);});
test('review must come from different family and refer to actual current content',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});await assert.rejects(()=>c.review(store,'a',{model:'another/deepseek',fingerprint:awaitableFake,findings:[],report:'inspected'}),/another model family/);await assert.rejects(()=>c.review(store,'a',{model:'glm',fingerprint:'stale',findings:[],report:'inspected'}),/stale/);});
const awaitableFake='unused';
test('repair escalation survives restart and blocks third Flash repair',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});for(let cycle=1;cycle<=4;cycle++){const depth=c.taskOf(await store.load(),'a').depth;await c.claim(store,'a',{workspace:dir,model:depth==='deep'?'moonshotai/kimi-k3':depth==='host'?'gpt-6-astra':'deepseek/flash'});await c.result(store,'a',{});await c.review(store,'a',{coverage:await syntheticCoverage(store,'a'),model:'z-ai/glm-flash',fingerprint:await c.fingerprint(dir),report:'wrong charge remains',findings:[{id:'wrong-charge',lens:'money',location:'app.txt',scenario:'checkout charges 11 instead of 10',evidence:'observed expected-versus-actual',consequence:'overcharge',blocking:true}]});await c.repair(store,'a');if(cycle===3){assert.equal(c.taskOf(await store.load(),'a').depth,'deep');await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'deepseek/flash'}),/Kimi/);}await c.resume(new c.Store(dir,'run'));}assert.equal(c.taskOf(await store.load(),'a').depth,'host');assert.equal(c.taskOf(await store.load(),'a').cycles,4);});
test('independent task unlocks dependent without global wave barrier',async t=>{const {dir,store}=await fixture(t);const other=join(dir,'.amale','isolated');await mkdir(other,{recursive:true});await c.plan(store,{tasks:[task('short'),task('long'),task('dependent',['short'])],integrationChecks:[]});await c.claim(store,'long',{workspace:other,model:'deepseek/flash'});await deliver(store,dir,'short');const next=await c.next(store);assert.equal(next.action,'route-dispatch');assert.ok((next as any).tasks.some((t:any)=>t.id==='dependent'));});
test('same workspace workers cannot race',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a'),task('b')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await assert.rejects(()=>c.claim(store,'b',{workspace:dir,model:'glm'}),/Conflicting/);});
test('resume preserves live owners and blocks abandoned effects',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash',pid:process.pid});await c.resume(store);assert.equal(c.taskOf(await store.load(),'a').status,'running');await store.transaction(s=>{c.taskOf(s,'a').owner!.pid=2147483647;});await c.resume(store);assert.equal(c.taskOf(await store.load(),'a').status,'blocked');assert.match(c.taskOf(await store.load(),'a').blocked!,/reconcile/);});
test('claim support remains pending after uncertain Jev judgment',async t=>{const {store}=await fixture(t);const answer=choiceAnswer({model:'typesafe/jev-1.13',answers:{selection:{type:'choice',choice:'yes',confidence:.4,probabilities:{yes:.55,no:.45}}}},{yes:'Supported',no:'Unsupported'});assert.equal(answer.choice,undefined);await store.transaction(s=>{s.decisions.push({id:'support',question:'Supported?',criteria:{yes:'supported',no:'unsupported'},state:{},revision:s.revision});});assert.equal((await c.next(store)).action,'host-decision');await hostDecision(store,'support','no','Missing evidence');assert.equal((await c.next(store)).action,'discover-specify-plan');assert.throws(()=>choiceAnswer({answers:{selection:{type:'choice',choice:'invented',confidence:1}}},{yes:'yes',no:'no'}));});
test('artifacts survive compaction and HTML escapes untrusted text',async t=>{const {store}=await fixture(t);const artifact=await store.artifact({evidence:'retain <script>alert(1)</script>'});assert.match(await store.readArtifact(artifact),/retain/);await store.transaction(s=>{s.intent='<script>alert(1)</script>';});const {path}=await statusHtml(store);assert.ok((await readFile(path,'utf8')).includes('&lt;script&gt;'));});
test('installer is rerunnable and refuses conflicting destinations',async t=>{const {dir}=await fixture(t);const old=process.env.CODEX_HOME;delete process.env.CODEX_HOME;try{await install(dir);const again=await install(dir);assert.ok(again.every(r=>r.status==='already linked'));const other=join(dir,'other');await mkdir(join(other,'.codex','skills','amale'),{recursive:true});await assert.rejects(()=>install(other),/Conflicting/);}finally{if(old)process.env.CODEX_HOME=old;}});

test('next advances checks, review and acceptance without repeated review',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});assert.equal((await c.next(store)).action,'check');await c.check(store,'a','test');assert.equal((await c.next(store)).action,'review');await c.review(store,'a',{coverage:await syntheticCoverage(store,'a'),model:'glm',fingerprint:await c.fingerprint(dir),findings:[],report:'Spec and Standards checked'});assert.equal((await c.next(store)).action,'accept');});
test('concurrent checkpoint commits serialize without losing events',async t=>{const {store}=await fixture(t);await Promise.all(Array.from({length:6},(_,i)=>store.transaction(async s=>{await new Promise(r=>setTimeout(r,10));c.event(s,'concurrent',i);})));assert.equal((await store.load()).events.filter(e=>e.type==='concurrent').length,6);});
test('check cannot credit a tree changed during execution',async t=>{const {dir,store}=await fixture(t);const a=task('a');a.checks=[{id:'test',command:process.execPath,args:['-e',"require('fs').writeFileSync('app.txt','bad amount')"]}];await c.plan(store,{tasks:[a],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});assert.equal((await c.check(store,'a','test')).changed,true);await c.review(store,'a',{coverage:await syntheticCoverage(store,'a'),model:'glm',fingerprint:await c.fingerprint(dir),findings:[],report:'review'});await assert.rejects(()=>c.accept(store,'a'),/stale/);});
test('invalidation carries escalation and invalidates downstream acceptance',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a'),task('b',['a'])],integrationChecks:[]});await deliver(store,dir,'a');await deliver(store,dir,'b');await store.transaction(s=>c.invalidateTree(s,'a','upstream contract changed'));let s=await store.load();assert.equal(c.taskOf(s,'b').integrated,undefined);assert.equal(c.taskOf(s,'b').status,'ready');assert.equal(c.taskOf(s,'a').cycles,1);await store.transaction(s=>c.invalidateTree(s,'a','another correction'));await store.transaction(s=>c.invalidateTree(s,'a','another correction'));s=await store.load();assert.equal(c.taskOf(s,'a').depth,'deep');await assert.rejects(()=>c.finish(store,['done']),/Incomplete/);});
test('unregistered final changes cannot slip through empty integration checks',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await deliver(store,dir);await writeFile(join(dir,'app.txt'),'bad amount');await assert.rejects(()=>c.finish(store,['done']),/changed after/);});

test('completed run resumes as done without mutation',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await deliver(store,dir);await c.finish(store,['amount checked']);const revision=(await store.load()).revision;assert.equal((await c.resume(store)).action,'done');assert.equal((await store.load()).revision,revision);});
test('resume invalidates obsolete downstream evidence',async t=>{const {dir,store}=await fixture(t);const a=join(dir,'.amale','a'),b=join(dir,'.amale','b');await mkdir(a,{recursive:true});await mkdir(b,{recursive:true});await writeFile(join(a,'amount'),'10');await c.plan(store,{tasks:[task('a'),task('b',['a'])],integrationChecks:[]});await deliver(store,a,'a');await deliver(store,b,'b');await writeFile(join(a,'amount'),'11');await c.resume(store);const state=await store.load();assert.equal(c.taskOf(state,'a').status,'ready');assert.equal(c.taskOf(state,'b').status,'ready');assert.equal(c.taskOf(state,'b').integrated,undefined);});
test('cross-host resume retains history and allows actual new host escalation',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a')],integrationChecks:[]});await store.transaction(s=>{const t=c.taskOf(s,'a');t.depth='host';t.cycles=4;});await c.resume(store,{kind:'claude',model:'claude-fable'});await c.claim(store,'a',{workspace:dir,model:'claude-fable'});const state=await store.load();assert.equal(state.host.model,'claude-fable');assert.equal(c.taskOf(state,'a').cycles,4);assert.ok(state.events.some(e=>e.type==='host-resumed'));});
test('contract amendment reopens descendants and retains repair ancestry',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a'),task('b',['a'])],integrationChecks:[]});await deliver(store,dir,'a');await deliver(store,dir,'b');await c.amend(store,{id:'a',reason:'New user-confirmed amount rule',task:{...task('a'),goal:'Apply the updated agreed amount rule'}});const s=await store.load();assert.equal(c.taskOf(s,'a').goal,'Apply the updated agreed amount rule');assert.equal(c.taskOf(s,'a').cycles,1);assert.equal(c.taskOf(s,'b').status,'ready');await assert.rejects(()=>c.amend(store,{id:'a',reason:'invalid cycle',task:task('a',['b'])}),/cycle/);});
test('missing check executable records failure and opens repair instead of repeating checks forever',async t=>{const {dir,store}=await fixture(t);const a=task('a');a.checks=[{id:'missing',command:join(dir,'missing-executable'),args:[]}];await c.plan(store,{tasks:[a],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});assert.equal((await c.check(store,'a','missing')).code,1);assert.equal((await c.next(store)).action,'repair-needed');await c.repair(store,'a');assert.equal(c.taskOf(await store.load(),'a').status,'repair');});
test('review focus preserves visibility of unrelated ready work',async t=>{const {dir,store}=await fixture(t);await c.plan(store,{tasks:[task('a'),task('b')],integrationChecks:[]});await c.claim(store,'a',{workspace:dir,model:'deepseek/flash'});await c.result(store,'a',{});const next=await c.next(store);assert.equal(next.action,'check');assert.ok(next.parallel?.ready.some(t=>t.id==='b'));});

test('missing review workspace exposes recovery and independent progress without losing evidence',async t=>{
 const {dir,store}=await fixture(t),workspace=join(dir,'.amale','missing-review');await mkdir(workspace);
 await c.plan(store,{tasks:[task('a'),task('independent')],integrationChecks:[]});
 await c.claim(store,'a',{workspace,model:'deepseek/flash'});await c.result(store,'a',{evidence:'retain original'});
 await store.transaction(s=>{c.taskOf(s,'a').cycles=2;c.taskOf(s,'a').depth='flash';});
 const before=await store.load(),original=c.taskOf(before,'a').output!;
 await rm(workspace,{recursive:true});
 const status=await c.packet(store);assert.ok('next' in status);
 for(const next of [await c.next(store),status.next]){assert.equal(next.action,'reconcile-workspace');assert.ok(next.parallel?.ready.some(t=>t.id==='independent'));}
 assert.equal((await store.load()).revision,before.revision);
 const resumed=await c.resume(store);assert.equal(resumed.action,'route-dispatch');assert.ok(resumed.parallel?.ready.some(t=>t.id==='independent'));
 const state=await store.load();assert.equal(c.taskOf(state,'a').status,'blocked');assert.equal(c.taskOf(state,'a').cycles,2);assert.equal(c.taskOf(state,'a').output,original);assert.match(await store.readArtifact(original),/retain original/);
 await c.resume(store);assert.equal(c.taskOf(await store.load(),'a').cycles,2);assert.equal(c.taskOf(await store.load(),'a').depth,'flash');
});

test('missing accepted workspace blocks stale descendants but preserves live ownership',async t=>{
 const {dir,store}=await fixture(t),a=join(dir,'.amale','a'),b=join(dir,'.amale','b'),live=join(dir,'.amale','live');
 for(const path of [a,b,live])await mkdir(path);
 await c.plan(store,{tasks:[task('a'),task('b',['a']),task('live',['a']),task('independent')],integrationChecks:[]});
 await deliver(store,a,'a');await deliver(store,b,'b');await c.claim(store,'live',{workspace:live,model:'deepseek/flash',pid:process.pid});
 const original=await store.load(),owner=c.taskOf(original,'live').owner,reviewArtifact=c.taskOf(original,'b').review!.artifact;
 await rm(a,{recursive:true});const resumed=await c.resume(store);assert.ok(resumed.parallel?.ready.some(t=>t.id==='independent'));
 const state=await store.load();for(const id of ['a','b']){assert.equal(c.taskOf(state,id).status,'blocked');assert.equal(c.taskOf(state,id).integrated,undefined);assert.equal(c.taskOf(state,id).cycles,0);}
 assert.equal(c.taskOf(state,'live').status,'running');assert.deepEqual(c.taskOf(state,'live').owner,owner);assert.match(await store.readArtifact(reviewArtifact),/inspected/);
 await c.result(store,'live',{});await c.check(store,'live','test');await c.review(store,'live',{model:'glm',fingerprint:await c.fingerprint(live),findings:[],report:'Synthetic review fixture'});
 await assert.rejects(()=>c.accept(store,'live'),/Unmet dependencies/);
 await assert.rejects(()=>c.finish(store,['incorrect stale completion']),/Incomplete/);
});
