import {clearCut} from './execution-fixture.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import * as c from '../scripts/core.ts';
import {scopeKey} from '../scripts/routing.ts';
async function fixture(t:any){const dir=await mkdtemp(join(tmpdir(),'amaleh-execution-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=await c.start(dir,{shape:clearCut,id:'run',host:{kind:'codex',model:'gpt-6-astra'},intent:'Delegate implementation',criteria:['Workers implement']});await c.plan(store,{tasks:['a','b'].map(id=>({id,title:id,goal:'Implement',phase:'one',deps:[],resources:[id],criteria:['Correct result'],kind:'code' as const,checks:[]})),integrationChecks:[]});return {dir,store};}
async function route(store:c.Store,dir:string,id='a',purpose:'worker'|'reviewer'='worker'){
 const decisionId=randomUUID();await store.transaction(s=>{const scope={taskId:id,purpose,workspace:dir,request:{}};s.decisions.push({id:decisionId,question:'Synthetic routing fixture',criteria:{worker:'deepseek/flash'},choice:'worker',source:'synthetic',revision:s.revision,state:{routing:{scope,key:scopeKey(s,scope),models:{worker:'deepseek/flash'}}}});});return decisionId;
}
test('plain coordinator and native model claims cannot bypass routing, including old callback',async t=>{const {dir,store}=await fixture(t);for(const model of ['gpt-6-astra','deepseek/flash','moonshot/kimi'])await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model,beforeClaim:()=>{}} as any),/Routed worker execution required/);assert.equal(c.taskOf(await store.load(),'a').status,'ready');});
test('claim consumes only a matching fresh worker route atomically',async t=>{const {dir,store}=await fixture(t);const routeDecisionId=await route(store,dir);const other=join(dir,'.amaleh','other');await mkdir(other,{recursive:true});for(const input of [{id:'b',workspace:dir,model:'deepseek/flash'},{id:'a',workspace:other,model:'deepseek/flash'},{id:'a',workspace:dir,model:'gpt-6-astra'}])await assert.rejects(()=>c.claim(store,input.id,{...input,routeDecisionId}));assert.ok(!(await store.load()).events.some(e=>e.type==='route-used'));await c.claim(store,'a',{workspace:dir,model:'deepseek/flash',routeDecisionId});const state=await store.load();assert.equal(c.taskOf(state,'a').execution?.kind,'routed-worker');assert.equal(state.events.filter(e=>e.type==='route-used').length,1);});
test('reviewer grant and stale task grant cannot authorize implementation',async t=>{const {dir,store}=await fixture(t);const reviewer=await route(store,dir,'a','reviewer');await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'deepseek/flash',routeDecisionId:reviewer}),/Worker route/);const worker=await route(store,dir);await store.transaction(s=>{s.tasks[0].goal='Changed';});await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'deepseek/flash',routeDecisionId:worker}),/changed/);});
test('explicit user exception is scoped and single-use across resume',async t=>{const {dir,store}=await fixture(t);const grant=await c.hostException(store,{id:'a',reason:'user-request',evidence:'Synthetic user expressly requested host implementation'});await c.resume(store);await assert.rejects(()=>c.claim(store,'b',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization}),/another task/);await c.claim(store,'a',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization});assert.equal(c.taskOf(await store.load(),'a').execution?.kind,'coordinator-exception');await store.transaction(s=>{s.tasks[0].status='ready';s.tasks[0].owner=undefined;});await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization}),/consumed/);});
test('host exceptions expire with changed contracts and cannot justify convenience fallback',async t=>{const {dir,store}=await fixture(t);for(const reason of ['small-task','network-blocked'])await assert.rejects(()=>c.hostException(store,{id:'a',reason:reason as any,evidence:'Convenient'}));const grant=await c.hostException(store,{id:'a',reason:'user-request',evidence:'Synthetic explicit instruction'});await store.transaction(s=>{s.tasks[0].criteria=['Changed'];});await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization}),/stale/);});
test('repair takeover requires exhausted ancestry and a recorded exception',async t=>{const {dir,store}=await fixture(t);await store.transaction(s=>{s.tasks[0].depth='host';});await assert.rejects(()=>c.hostException(store,{id:'a',reason:'repair-escalation',evidence:'Not exhausted'}),/not exhausted/);await store.transaction(s=>{s.tasks[0].cycles=4;});await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'gpt-6-astra'}),/recorded/);const grant=await c.hostException(store,{id:'a',reason:'repair-escalation',evidence:'Persistent repair attempts exhausted; host diagnosis required'});await c.claim(store,'a',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization});});
test('legacy in-flight claims require reconciliation rather than silent continuation',async t=>{const {dir,store}=await fixture(t);await store.transaction(s=>{s.tasks[0].status='running';s.tasks[0].workspace=dir;});assert.equal((await c.next(store)).action,'reconcile-execution');await assert.rejects(()=>c.result(store,'a',{}),/Legacy claim/);});

test('legacy reconciliation confirms exact stopped ownership and preserves artifacts for requeue',async t=>{const {dir,store}=await fixture(t);await store.transaction(s=>{Object.assign(s.tasks[0],{status:'running',workspace:dir,owner:{pid:process.pid,host:'local',operation:'legacy'},output:'retained-artifact',cycles:2});});await assert.rejects(()=>c.reconcileExecution(store,{id:'a',operation:'legacy',confirmedStopped:false,evidence:'Unconfirmed'}));await assert.rejects(()=>c.reconcileExecution(store,{id:'a',operation:'other',confirmedStopped:true,evidence:'Wrong owner'}));await c.reconcileExecution(store,{id:'a',operation:'legacy',confirmedStopped:true,evidence:'Synthetic host verified task execution stopped; coordinator remains alive'});const state=await store.load();assert.equal(state.tasks[0].status,'blocked');assert.equal(state.tasks[0].output,'retained-artifact');assert.equal(state.tasks[0].cycles,2);assert.equal(state.tasks[0].owner,undefined);assert.ok(state.events.some(e=>e.type==='legacy-execution-reconciled'));});
test('changed repair policy invalidates a previously granted host exception',async t=>{const {dir,store}=await fixture(t);await store.transaction(s=>{s.tasks[0].depth='host';s.tasks[0].cycles=4;});const grant=await c.hostException(store,{id:'a',reason:'repair-escalation',evidence:'Synthetic exhausted repairs'});await store.transaction(s=>{s.config.flashRepairCycles=5;});await assert.rejects(()=>c.claim(store,'a',{workspace:dir,model:'gpt-6-astra',hostAuthorization:grant.authorization}),/stale/);});
