import type { EffortState } from './effort.ts';
import { mkdir, readFile, writeFile, rename, readdir, stat, rm, realpath } from 'node:fs/promises';
import { resolve, join, relative, isAbsolute, sep } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { hostname } from 'node:os';

export type Command = { command:string; args:string[] };
export type Check = Command & { id:string };
export type Finding = { id:string; lens:string; location:string; scenario:string; evidence:string; consequence:string; blocking:boolean; disposition?:'open'|'resolved'|'refuted'; resolution?:string };
export type ReviewCoverage = { id:string; status:'covered'|'finding'|'unreviewed'|'not-applicable'; evidence:string };
export type Task = { id:string; title:string; goal:string; phase:string; deps:string[]; resources:string[]; criteria:string[]; checks:Check[]; kind:'code'|'research'|'plan'; status:'ready'|'running'|'review'|'repair'|'accepted'|'blocked'; workspace?:string; activity?:{kind:'check'|'review';owner:{pid:number;coordinatorPid?:number;host:string;operation:string};checkId?:string}; owner?:{pid:number;host:string;operation:string}; author?:string; family?:string; fingerprint?:string; output?:string; receipts:{id:string;code:number;fingerprint:string;artifact:string}[]; review?:{family:string;fingerprint:string;findings:Finding[];artifact:string;coverage?:ReviewCoverage[]}; cycles:number; depth:'flash'|'deep'|'host'; blocked?:string; integrated?:string };
export type Decision = { purpose?:'requirement'|'workflow'; id:string; question:string; criteria:Record<string,string>; state:unknown; revision:number; choice?:string; source?:string; confidence?:number; reason?:string; artifact?:string };
export type TaskInput = Pick<Task,'id'|'title'|'goal'|'phase'|'deps'|'resources'|'criteria'|'checks'|'kind'>;
export type ModelPool = { role:string; models:string[]; requiredInputs:string[]; requiresTools:boolean; notes:string };
export type Run = { schema:1; id:string; workspace:string; host:{kind:string;model:string}; effort?:EffortState; intent:string; criteria:string[]; constraints:string[]; decisions:Decision[]; tasks:Task[]; revision:number; status:'active'|'blocked'|'complete'; blocked?:string; config:{flashRepairCycles:number;deepRepairCycles:number;maxWorkers:number}; modelPools?:ModelPool[]; integrationChecks:Check[]; integrationReceipts:Task['receipts']; acceptance?:{fingerprint:string;claims:string[]}; events:{at:string;type:string;detail:unknown}[] };
export function invariant(value:unknown,message:string):asserts value { if(!value) throw new Error(message); }
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export const idCheck=(id:string)=>invariant(typeof id==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/.test(id),'Invalid identifier');
export function validCommand(c:Command) { invariant(c&&typeof c.command==='string'&&c.command.length>0&&Array.isArray(c.args)&&c.args.every(a=>typeof a==='string'),'Commands require an executable and argument array'); }
export function validateTasks(tasks:TaskInput[]) {
 const ids=new Set<string>(); for(const t of tasks){idCheck(t.id);invariant(!ids.has(t.id),'Duplicate task ID');ids.add(t.id);invariant(t.goal&&t.title&&Array.isArray(t.deps)&&Array.isArray(t.resources)&&Array.isArray(t.criteria)&&t.criteria.length&&Array.isArray(t.checks),'Task needs goal, title, dependencies, resources, criteria and checks');invariant(['code','research','plan'].includes(t.kind),'Invalid task kind'); for(const c of t.checks){idCheck(c.id);validCommand(c);} invariant(new Set(t.checks.map(c=>c.id)).size===t.checks.length,'Duplicate check ID');}
 const active=new Set<string>(),done=new Set<string>(); const visit=(id:string)=>{invariant(!active.has(id),'Dependency cycle');if(done.has(id))return;active.add(id);for(const dep of tasks.find(t=>t.id===id)!.deps){invariant(ids.has(dep),'Missing dependency');visit(dep);}active.delete(id);done.add(id);};for(const id of ids)visit(id);
}
export const taskOf=(s:Run,id:string)=>{const t=s.tasks.find(t=>t.id===id);invariant(t,'Unknown task');return t;};
export function family(model:string):string { if(/deepseek/i.test(model))return 'deepseek';if(/glm|z-ai/i.test(model))return 'glm';if(/kimi|moonshot/i.test(model))return 'kimi';if(/claude|anthropic|fable/i.test(model))return 'claude';if(/astra|gpt|openai/i.test(model))return 'openai';return model.split('/')[0]; }
export function conflict(a:Task,b:Task){return !a.workspace||!b.workspace||a.workspace===b.workspace||a.resources.some(r=>b.resources.some(s=>r==='*'||s==='*'||r===s||r.startsWith(s+'/')||s.startsWith(r+'/')));}
const ignored=new Set(['.git','.amale','node_modules','.DS_Store']);
export async function fingerprint(workspace:string):Promise<string>{
 const entries:string[]=[]; async function walk(dir:string){for(const ent of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(ignored.has(ent.name))continue;const path=join(dir,ent.name),name=relative(workspace,path).split(sep).join('/');if(ent.isSymbolicLink()){const {readlink}=await import('node:fs/promises');entries.push(`${name}:link:${await readlink(path)}`);}else if(ent.isDirectory())await walk(path);else if(ent.isFile())entries.push(`${name}:${hash((await readFile(path)).toString('base64'))}`);}}await walk(workspace);return hash(entries.join('\n'));
}
export class Store {
 root:string;
 constructor(workspace:string,runId:string){idCheck(runId);this.root=join(resolve(workspace),'.amale','runs',runId);}
 async load():Promise<Run>{const names=(await readdir(this.root)).filter(n=>/^revision-\d{9}\.json$/.test(n)).sort();invariant(names.length,'Run not found');const state=JSON.parse(await readFile(join(this.root,names.at(-1)!), 'utf8'));invariant(state.schema===1,'Unsupported run schema');validateTasks(state.tasks);return state;}
 async artifact(data:unknown):Promise<string>{await mkdir(join(this.root,'artifacts'),{recursive:true});const text=typeof data==='string'?data:JSON.stringify(data,null,2),id=hash(text);await writeFile(join(this.root,'artifacts',id+'.json'),text,{flag:'wx'}).catch((e)=>{if(e.code!=='EEXIST')throw e;});return id;}
 async readArtifact(id:string){invariant(/^[a-f0-9]{64}$/.test(id),'Invalid artifact ID');return readFile(join(this.root,'artifacts',id+'.json'),'utf8');}
 async lock(){await mkdir(this.root,{recursive:true});const path=join(this.root,'lock');for(let attempt=0;;attempt++){try{await mkdir(path);break;}catch(e){if((e as NodeJS.ErrnoException).code!=='EEXIST')throw e;if(attempt>=100)throw new Error('Run is locked. Inspect owner; unlock only after verifying abandonment.');await new Promise(r=>setTimeout(r,50));}}try{await writeFile(join(path,'owner.json'),JSON.stringify({pid:process.pid,host:hostname()}));}catch(e){await rm(path,{recursive:true});throw e;}return ()=>rm(path,{recursive:true});}
 async unlock(){const path=join(this.root,'lock');const owner=JSON.parse(await readFile(join(path,'owner.json'),'utf8'));invariant(owner.host===hostname(),'Cannot verify remote owner');let alive=true;try{process.kill(owner.pid,0);}catch(e){if((e as NodeJS.ErrnoException).code==='ESRCH')alive=false;}invariant(!alive,'Lock owner is alive');await rm(path,{recursive:true});}
 async transaction<T>(change:(s:Run)=>Promise<T>|T):Promise<T>{const release=await this.lock();try{const s=await this.load();invariant(s.status!=='complete','Completed run is immutable; start a new run');const result=await change(s);s.revision++;await this.save(s);return result;}finally{await release();}}
 async save(s:Run){const name=`revision-${String(s.revision).padStart(9,'0')}.json`,temp=join(this.root,randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(s,null,2));await rename(temp,join(this.root,name));}
}
export function event(s:Run,type:string,detail:unknown){s.events.push({at:new Date().toISOString(),type,detail});}
export async function start(workspace:string,input:{id:string;host:Run['host'];intent:string;criteria:string[];constraints?:string[]}):Promise<Store>{
 invariant(input.intent&&input.criteria?.length&&input.host?.kind&&input.host?.model,'Intent, acceptance criteria and actual host identity required');const store=new Store(await realpath(workspace),input.id),release=await store.lock();try{invariant(!(await readdir(store.root)).some(n=>n.startsWith('revision-')),'Run already exists: resume it');const s:Run={schema:1,id:input.id,workspace:await realpath(workspace),host:input.host,intent:input.intent,criteria:input.criteria,constraints:input.constraints??[],decisions:[],tasks:[],revision:0,status:'active',config:{flashRepairCycles:2,deepRepairCycles:1,maxWorkers:3},integrationChecks:[],integrationReceipts:[],events:[]};event(s,'started',{host:input.host});await store.save(s);return store;}finally{await release();}}
export async function plan(store:Store,input:{tasks:TaskInput[];integrationChecks:Check[]}){await store.transaction(s=>{invariant(Array.isArray(input.tasks)&&Array.isArray(input.integrationChecks),'Tasks and integrationChecks required');const existing=new Map(s.tasks.map(t=>[t.id,t]));const tasks=input.tasks.map(t=>{const old=existing.get(t.id);if(old){invariant(JSON.stringify([old.goal,old.deps,old.criteria,old.checks])===JSON.stringify([t.goal,t.deps,t.criteria,t.checks]),'Existing task contract changed; invalidate/replan explicitly');return old;}return {...t,status:'ready' as const,cycles:0,depth:'flash' as const,receipts:[]};});invariant([...existing.keys()].every(id=>tasks.some(t=>t.id===id)),'Cannot drop task history');validateTasks(tasks);input.integrationChecks.forEach(validCommand);s.tasks=tasks;s.integrationChecks=input.integrationChecks;s.integrationReceipts=[];event(s,'planned',{tasks:tasks.map(t=>t.id)});});}
// Coverage is an explicit reviewer attestation, not proof that all defects were found.
export function reviewObligations(s:Run,t:Task):{id:string;question:string}[]{return [
 ...t.criteria.map((criterion,i)=>({id:`criterion:${i+1}`,question:`Spec: inspect the actual behavior satisfying task criterion: ${criterion}`})),
 ...s.criteria.map((criterion,i)=>({id:`outcome:${i+1}`,question:`Spec: trace this task's contribution, preservation and integration dependencies for run outcome: ${criterion}`})),
 {id:'standards',question:'Standards: inspect applicable repository instructions and conventions; distinguish real violations from preferences.'},
 {id:'boundaries',question:'Trace changed inputs, outputs and affected callers; inspect malformed, empty and rejected inputs, and contract compatibility.'},
 {id:'lifecycle',question:'Trace reachable success, failure, interruption and recovery exits; verify durable evidence, cleanup and terminal ordering.'},
 {id:'parallelism',question:'For actual overlap, retry or shared-state paths, inspect ownership, capacity, conflicts and the complete eligible work frontier.'},
 {id:'integration',question:'Trace affected consumers and integrated outcomes; check deterministic rejection before external effects and verify evidence against the actual artifacts.'}
];}
function validateReviewCoverage(s:Run,t:Task,coverage:ReviewCoverage[]){
 const required=reviewObligations(s,t);invariant(Array.isArray(coverage),'Review coverage must be an array');
 invariant(coverage.length===required.length&&new Set(coverage.map(c=>c?.id)).size===required.length&&coverage.every(c=>c&&required.some(r=>r.id===c.id)),'Review coverage must include every obligation exactly once; missing, duplicate or unknown IDs');
 for(const c of coverage){invariant(['covered','finding','unreviewed','not-applicable'].includes(c.status)&&typeof c.evidence==='string'&&!!c.evidence.trim(),'Review coverage requires a valid status and nonempty evidence');invariant(c.status!=='not-applicable'||!/^(criterion|outcome):/.test(c.id),'Criterion and outcome coverage cannot be not-applicable');}
}
function reviewCoverageDebt(s:Run,t:Task){return reviewObligations(s,t).filter(required=>{
 const matches=t.review?.coverage?.filter(c=>c.id===required.id)??[];
 return matches.length!==1||!matches[0].evidence?.trim()||!(matches[0].status==='covered'||matches[0].status==='not-applicable'&&!/^(criterion|outcome):/.test(required.id));
});}
async function reviewAction(s:Run,t:Task){if(t.activity)return {action:'await-verification',task:t.id,activity:t.activity}; const unmet=t.deps.filter(id=>taskOf(s,id).status!=='accepted'||!taskOf(s,id).integrated);if(unmet.length)return {action:'reconcile-dependencies',task:t.id,dependencies:unmet}; let fp:string; try{fp=await fingerprint(t.workspace!);}catch(error){if(!workspaceUnavailable(error))throw error;return {action:'reconcile-workspace',task:t.id,workspace:t.workspace,reason:(error as Error).message,recovery:'Restore workspace access, or resume to block affected work while independent tasks continue'};} const missing=t.checks.filter(c=>!t.receipts.some(r=>r.id===c.id&&r.fingerprint===fp&&r.code===0)); if(t.receipts.some(r=>r.code!==0))return {action:'repair-needed',task:t.id}; if(missing.length)return {action:'check',task:t.id,checks:missing}; if(!t.review||t.review.fingerprint!==fp)return {action:'review',tasks:[{id:t.id,author:t.family,workspace:t.workspace}]}; if(t.review.findings.some(f=>f.blocking&&f.disposition==='open'))return {action:'triage-repair',task:t.id,findings:t.review.findings}; const coverage=reviewCoverageDebt(s,t); if(coverage.length)return {action:'review-evidence-needed',task:t.id,obligations:coverage.map(o=>({...o,evidence:t.review?.coverage?.find(c=>c.id===o.id)?.evidence})),reviewArtifact:t.review.artifact}; return {action:'accept',task:t.id};}
async function nextAction(s:Run,reviewActions:Map<string,Awaited<ReturnType<typeof reviewAction>>>){if(s.status==='complete')return {action:'done',run:s.id,acceptance:s.acceptance};if(s.status==='blocked')return {action:'intervention',reason:s.blocked};if(s.effort?.request)return {action:s.effort.request.status==='running'?'await-host-effort':'execute-host-effort',model:s.effort.model,base:s.effort.base,modes:s.effort.modes,...s.effort.request};const pending=s.decisions.find(d=>!d.choice);if(pending)return {action:'host-decision',decision:pending};if(!s.tasks.length)return {action:'discover-specify-plan',intent:s.intent,criteria:s.criteria};const review=s.tasks.filter(t=>t.status==='review');if(review.length)return reviewActions.get(review[0].id)!;const repair=s.tasks.filter(t=>t.status==='repair');if(repair.length)return {action:'repair',tasks:repair.map(t=>({id:t.id,depth:t.depth,cycles:t.cycles,findings:t.review?.findings.filter(f=>f.blocking&&f.disposition!=='resolved'&&f.disposition!=='refuted')}))};const running=s.tasks.filter(t=>t.status==='running');const ready=s.tasks.filter(t=>t.status==='ready'&&t.deps.every(id=>taskOf(s,id).status==='accepted'&&!!taskOf(s,id).integrated));if(ready.length&&running.length<s.config.maxWorkers)return {action:'route-dispatch',tasks:ready.map(t=>({id:t.id,goal:t.goal,criteria:t.criteria})),available:Math.max(0,s.config.maxWorkers-running.length)};const integrate=s.tasks.filter(t=>t.status==='accepted'&&!t.integrated);if(integrate.length)return {action:'integrate',tasks:integrate.map(t=>t.id)};if(running.length)return {action:'await-workers',tasks:running.map(t=>({id:t.id,owner:t.owner}))};const blocked=s.tasks.filter(t=>t.status==='blocked');if(blocked.length)return {action:'resolve-blockers',tasks:blocked.map(t=>({id:t.id,reason:t.blocked}))};return {action:'verify-feature',criteria:s.criteria,checks:s.integrationChecks};}
export const activeTasks=(s:Run)=>s.tasks.filter(t=>t.status==='running'||!!t.activity);
export async function acquireActivity(store:Store,id:string,kind:'check'|'review',checkId?:string,beforeStart?:(s:Run)=>void|Promise<void>){return store.transaction(async s=>{const t=taskOf(s,id);invariant(t.status==='review'&&t.workspace,'Task not awaiting verification');invariant(!t.activity,'Task verification already active');const live=activeTasks(s);invariant(live.length<s.config.maxWorkers,'Worker capacity reached');invariant(!live.some(other=>conflict(t,other)),'Conflicting live task');await beforeStart?.(s);const operation=randomUUID();t.activity={kind,checkId,owner:{pid:process.pid,coordinatorPid:process.pid,host:hostname(),operation}};event(s,'activity-started',{id,...t.activity});return operation;});}
export async function activitySpawned(store:Store,id:string,operation:string,pid:number){await store.transaction(s=>{const activity=taskOf(s,id).activity;invariant(activity?.owner.operation===operation,'Verification ownership changed');activity.owner.pid=pid;});}
export async function releaseActivity(store:Store,id:string,operation:string){await store.transaction(s=>{const t=taskOf(s,id);if(t.activity?.owner.operation===operation){t.activity=undefined;event(s,'activity-finished',{id,operation});}});}
export async function claim(store:Store,id:string,input:{workspace:string;model:string;pid?:number;beforeClaim?:(s:Run)=>void}){await store.transaction(async s=>{const t=taskOf(s,id);invariant(['ready','repair'].includes(t.status)&&!t.activity,'Task is not executable');invariant(t.deps.every(id=>taskOf(s,id).status==='accepted'&&!!taskOf(s,id).integrated),'Unmet dependencies');invariant(input.model,'Actual author model required');if(t.depth==='deep')invariant(family(input.model)==='kimi','Kimi diagnosis required before another Flash repair');if(t.depth==='host')invariant(input.model===s.host.model,'Main model must take over');t.workspace=await realpath(input.workspace);const live=activeTasks(s).filter(other=>other.id!==id);invariant(live.length<s.config.maxWorkers,'Worker capacity reached');invariant(!live.some(other=>conflict(t,other)),'Conflicting live task');input.beforeClaim?.(s);t.author=input.model;t.family=family(input.model);t.status='running';t.owner={pid:input.pid??process.pid,host:hostname(),operation:randomUUID()};t.receipts=[];t.integrated=undefined;s.integrationReceipts=[];event(s,'claimed',{id,workspace:t.workspace,model:input.model,operation:t.owner.operation});});}
export async function result(store:Store,id:string,output:unknown){const artifact=await store.artifact(output);await store.transaction(async s=>{const t=taskOf(s,id);invariant(t.status==='running'&&t.workspace,'Task not running');t.fingerprint=await fingerprint(t.workspace);t.output=artifact;t.status='review';t.owner=undefined;event(s,'result',{id,artifact,fingerprint:t.fingerprint});});}
export async function execute(command:Command,cwd:string,onSpawn?:(pid:number)=>Promise<void>):Promise<{code:number;stdout:string;stderr:string}>{validCommand(command);return new Promise((done,fail)=>{const child=spawn(command.command,command.args,{cwd,shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);let ownershipError:unknown;const ownership=Promise.resolve().then(()=>child.pid?onSpawn?.(child.pid):undefined).catch(error=>{ownershipError=error;child.kill();});child.on('error',fail);child.on('close',code=>{void ownership.then(()=>{if(ownershipError)fail(ownershipError);else done({code:code??1,stdout,stderr});});});});}
export async function check(store:Store,id:string|undefined,checkId:string){const s=await store.load(),t=id?taskOf(s,id):undefined;const c=(t?t.checks:s.integrationChecks).find(c=>c.id===checkId);invariant(c,'Unknown check');const cwd=t?.workspace??s.workspace;const operation=id?await acquireActivity(store,id,'check',checkId):undefined;try{const before=await fingerprint(cwd);let receipt:{code:number;stdout:string;stderr:string};try{receipt=await execute(c,cwd,id&&operation?pid=>activitySpawned(store,id,operation,pid):undefined);}catch(error){receipt={code:1,stdout:"",stderr:"Check could not execute: "+(error as Error).message};}const after=await fingerprint(cwd);const artifact=await store.artifact({command:c,cwd,before,after,...receipt});await store.transaction(current=>{const target=id?taskOf(current,id):undefined;invariant(!target||target.workspace===cwd,'Task workspace changed during check');const list=target?target.receipts:current.integrationReceipts;const prior=list.findIndex(r=>r.id===checkId);if(prior>=0)list.splice(prior,1);list.push({id:checkId,code:receipt.code,fingerprint:before,artifact});event(current,'check',{id,checkId,code:receipt.code,artifact});});return {code:receipt.code,artifact,changed:before!==after};}finally{if(id&&operation)await releaseActivity(store,id,operation);}}
export async function addReviewCheck(store:Store,id:string,check:Check){await store.transaction(s=>{
 const t=taskOf(s,id);invariant(t.status==='review'&&!t.activity,'Review evidence checks require an idle task awaiting review');
 idCheck(check.id);validCommand(check);invariant(!t.checks.some(c=>c.id===check.id),'Duplicate check ID');
 t.checks.push(check);t.review=undefined;event(s,'review-check-added',{id,check});
});}
export async function review(store:Store,id:string,input:{model:string;findings:Finding[];fingerprint:string;report:string;coverage?:ReviewCoverage[]}){const artifact=await store.artifact(input);await store.transaction(async s=>{const t=taskOf(s,id);invariant(t.status==='review'&&t.workspace,'Task not awaiting review');invariant(input.model&&family(input.model)!==t.family,'Review requires another model family');invariant(input.fingerprint===await fingerprint(t.workspace),'Review evidence is stale');invariant(Array.isArray(input.findings)&&typeof input.report==='string'&&input.report.length>0,'Review report required');for(const f of input.findings)invariant(f.id&&f.lens&&f.location&&f.scenario&&f.evidence&&f.consequence&&typeof f.blocking==='boolean','Finding lacks evidence');if(input.coverage!==undefined)validateReviewCoverage(s,t,input.coverage);const findings=input.findings.map(f=>({...f,disposition:'open' as const}));t.review={family:family(input.model),fingerprint:input.fingerprint,findings,artifact,coverage:input.coverage};event(s,'review',{id,artifact});});}
export async function repair(store:Store,id:string){await store.transaction(s=>{const t=taskOf(s,id);invariant(t.status==='review'&&!t.activity,'Task is not in review or verification remains active');invariant(t.review?.findings.some(f=>f.blocking&&f.disposition==='open')||t.receipts.some(r=>r.code!==0),'No blocking review or failing check');t.cycles++;t.depth=t.cycles>s.config.flashRepairCycles+s.config.deepRepairCycles?'host':t.cycles>s.config.flashRepairCycles?'deep':'flash';t.status='repair';event(s,'repair',{id,cycle:t.cycles,depth:t.depth});});}
export async function accept(store:Store,id:string){await store.transaction(async s=>{const t=taskOf(s,id);invariant(t.status==='review'&&t.workspace&&t.output&&t.review&&!t.activity,'Result and independent review required; verification must be idle');invariant(t.deps.every(id=>taskOf(s,id).status==='accepted'&&!!taskOf(s,id).integrated),'Unmet dependencies; reconcile upstream evidence before acceptance');const fp=await fingerprint(t.workspace);invariant(t.review.fingerprint===fp,'Review stale');invariant(!t.review.findings.some(f=>f.blocking&&f.disposition==='open'),'Blocking findings remain');invariant(t.checks.every(c=>t.receipts.some(r=>r.id===c.id&&r.code===0&&r.fingerprint===fp)),'Required checks missing, failed, or stale');invariant(!reviewCoverageDebt(s,t).length,'Review coverage incomplete; obtain missing evidence and a corrected independent report');t.status='accepted';t.fingerprint=fp;event(s,'accepted',{id,fp});});}
export async function integrated(store:Store,id:string,evidence:string){await store.transaction(async s=>{const t=taskOf(s,id);invariant(t.status==='accepted'&&evidence,'Accepted task and integration evidence required');invariant(t.workspace&&t.fingerprint===await fingerprint(t.workspace),'Accepted workspace changed');t.integrated=await fingerprint(s.workspace);event(s,'integrated',{id,evidence,fingerprint:t.integrated});s.integrationReceipts=[];});}
export async function finish(store:Store,claims:string[]){await store.transaction(async s=>{invariant(!s.effort?.request,'Host effort pass is unfinished');invariant(s.tasks.length&&s.tasks.every(t=>t.status==='accepted'&&t.integrated),'Incomplete tasks');const fp=await fingerprint(s.workspace);invariant(s.tasks.some(t=>t.integrated===fp),'Integrated content changed after recorded integration');invariant(!s.decisions.some(d=>!d.choice),'Unresolved semantic decision');invariant(s.integrationChecks.every(c=>s.integrationReceipts.some(r=>r.id===c.id&&r.code===0&&r.fingerprint===fp)),'Integration checks missing, failed or stale');invariant(Array.isArray(claims)&&claims.length===s.criteria.length&&claims.every(c=>typeof c==='string'&&c.trim()),'Evidence explanation required for every outcome');s.acceptance={fingerprint:fp,claims};s.status='complete';event(s,'finished',s.acceptance);});}
const workspaceUnavailable=(error:unknown)=>['ENOENT','ENOTDIR','EACCES','EPERM'].includes((error as NodeJS.ErrnoException).code??'');
function quarantineWorkspace(s:Run,id:string,reason:string){
 const affected=new Set([id]);let changed=true;
 while(changed){changed=false;for(const t of s.tasks)if(!affected.has(t.id)&&t.deps.some(dep=>affected.has(dep))){affected.add(t.id);changed=true;}}
 const live:string[]=[];
 for(const t of s.tasks)if(affected.has(t.id)){
  if(t.status==='running'||t.activity){live.push(t.id);continue;}
  if(t.status==='blocked')continue;
  t.status='blocked';t.blocked=`Workspace recovery required for ${id}: ${reason}`;t.integrated=undefined;t.receipts=[];t.review=undefined;
 }
 s.integrationReceipts=[];event(s,'workspace-unavailable',{id,reason,affected:[...affected],live});
}
export async function resume(store:Store,host?:Run['host']){
 const existing=await store.load();if(existing.status==='complete')return next(store);
 await store.transaction(async s=>{
  s.status='active';s.blocked=undefined;
  if(host){invariant(host.kind&&host.model,'Actual resumed host identity required');if(host.model!==s.host.model||host.kind!==s.host.kind){invariant(!s.effort?.request,'Reconcile active effort execution before switching hosts');s.effort=undefined;}event(s,'host-resumed',{previous:s.host,current:host});s.host=host;}
  for(const t of s.tasks)if(t.status==='running'&&t.owner){let alive=true;if(t.owner.host===hostname()){try{process.kill(t.owner.pid,0);}catch(e){if((e as NodeJS.ErrnoException).code==='ESRCH')alive=false;}}if(!alive){t.status='blocked';t.blocked='Interrupted operation: reconcile artifacts and side effects before requeue';t.owner=undefined;}}
  for(const t of s.tasks)if(t.activity){const owner=t.activity.owner;let alive=true;if(owner.host===hostname()){alive=[owner.pid,owner.coordinatorPid].filter((pid):pid is number=>pid!==undefined).some(pid=>{try{process.kill(pid,0);return true;}catch(e){return (e as NodeJS.ErrnoException).code!=='ESRCH';}});}if(!alive){event(s,'activity-interrupted',{id:t.id,activity:t.activity});t.activity=undefined;t.status='blocked';t.blocked='Interrupted verification: reconcile artifacts and side effects before requeue';}}
  const stale:string[]=[],unavailable:{id:string;reason:string}[]=[];for(const t of s.tasks)if(['review','accepted'].includes(t.status)&&t.workspace){try{const fp=await fingerprint(t.workspace);if(t.status==='accepted'&&t.fingerprint!==fp)stale.push(t.id);}catch(error){if(!workspaceUnavailable(error))throw error;unavailable.push({id:t.id,reason:(error as Error).message});}}
  for(const fault of unavailable)if(['review','accepted'].includes(taskOf(s,fault.id).status))quarantineWorkspace(s,fault.id,fault.reason);
  for(const id of stale)if(taskOf(s,id).status==='accepted')invalidateTree(s,id,'Accepted workspace changed since verification');
  event(s,'resumed',{});
 });return next(store);
}
export async function packet(store:Store,id?:string){
 const s=await store.load(),t=id?taskOf(s,id):undefined;
 const decision=(d:Decision)=>({id:d.id,question:d.question,choice:d.choice,answer:d.choice?d.criteria[d.choice]:undefined,reason:d.reason,artifact:d.artifact});
 const common={run:s.id,host:s.host,intent:s.intent,criteria:s.criteria,constraints:s.constraints,artifactDirectory:join(store.root,'artifacts')};
 if(t){
  const relevant=new Set([t.id]);const visit=(id:string)=>{for(const dep of taskOf(s,id).deps)if(!relevant.has(dep)){relevant.add(dep);visit(dep);}};visit(t.id);
  return {...common,task:t,decisions:s.decisions.filter(d=>{
   const routing=(d.state as any)?.routing;
   // Unscoped intent/technical decisions are retained; never discard them by recency.
   return d.choice&&(!routing?.scope?.taskId||relevant.has(routing.scope.taskId));
  }).map(decision),dependencies:s.tasks.filter(d=>d.id!==t.id&&relevant.has(d.id)).map(d=>({id:d.id,goal:d.goal,criteria:d.criteria,status:d.status,output:d.output,review:d.review?.artifact,integrated:d.integrated})),
  durableState:join(store.root,`revision-${String(s.revision).padStart(9,'0')}.json`)};
 }
 return {...common,effort:s.effort,modelPools:s.modelPools,decisions:s.decisions.filter(d=>d.choice).map(decision),phaseStatus:s.tasks.map(t=>({id:t.id,phase:t.phase,status:t.status,deps:t.deps,integrated:!!t.integrated})),next:await next(store)};
}

export function invalidateTree(s:Run,id:string,reason:string){
 invariant(reason,'Invalidation reason required');const root=taskOf(s,id),affected=new Set([id]);let changed=true;while(changed){changed=false;for(const t of s.tasks)if(!affected.has(t.id)&&t.deps.some(dep=>affected.has(dep))){affected.add(t.id);changed=true;}}
 invariant(!s.tasks.some(t=>affected.has(t.id)&&(t.status==='running'||!!t.activity)),'Affected task is still running; reconcile ownership before invalidation');
 for(const t of s.tasks)if(affected.has(t.id)){
  // Every repeated implementation attempt consumes the same ancestry counter.
  if(t.output||t.review){t.cycles++;t.depth=t.cycles>s.config.flashRepairCycles+s.config.deepRepairCycles?'host':t.cycles>s.config.flashRepairCycles?'deep':'flash';}
  t.status='ready';t.integrated=undefined;t.receipts=[];t.review=undefined;
 }
 s.integrationReceipts=[];event(s,'invalidated',{id,reason,affected:[...affected]});
}

export async function amend(store:Store,input:{id:string;reason:string;task:TaskInput}){await store.transaction(s=>{invariant(input.task.id===input.id,'Amend retains task identity');invalidateTree(s,input.id,input.reason);const t=taskOf(s,input.id);for(const key of ['title','goal','phase','deps','resources','criteria','checks','kind'] as const)(t as any)[key]=input.task[key];validateTasks(s.tasks);event(s,'contract-amended',{id:input.id,reason:input.reason});});}

export type ParallelAction={task:string;action:string;workspace?:string;resources:string[];checks?:Check[];[key:string]:unknown};
export async function next(store:Store){
 const s=await store.load();
 const reviewed=s.status==='active'?s.tasks.filter(t=>t.status==='review'):[];
 const reviewActions=new Map(await Promise.all(reviewed.map(async t=>[t.id,await reviewAction(s,t)] as const)));
 const action=await nextAction(s,reviewActions);
 const running=activeTasks(s);
 const ready=s.tasks.filter(t=>t.status==='ready'&&t.deps.every(id=>taskOf(s,id).status==='accepted'&&!!taskOf(s,id).integrated));
 const actions=s.tasks.flatMap<ParallelAction>(t=>{
  if(s.status!=='active')return [];
  const scope={task:t.id,workspace:t.workspace,resources:t.resources};
  if(t.status==='review')return [{...scope,...reviewActions.get(t.id)!}];
  if(t.status==='repair')return [{...scope,action:'repair',depth:t.depth,cycles:t.cycles}];
  if(t.status==='accepted'&&!t.integrated)return [{...scope,workspace:s.workspace,action:'integrate'}];
  return [];
 });
 // A suggested verification batch, not permission to run simultaneous integration or conflicting checks.
 const independent:typeof actions=[];const used:Task[]=[...running];
 for(const item of actions){const t=taskOf(s,item.task);if(!['check','review'].includes(item.action??'')||!t.workspace||used.some(other=>conflict(t,other)))continue;
  if(independent.length>=Math.max(0,s.config.maxWorkers-running.length))break;independent.push(item);used.push(t);
 }
 return {...action,parallel:s.status==='active'?{available:Math.max(0,s.config.maxWorkers-running.length),ready:ready.map(t=>({id:t.id,goal:t.goal,resources:t.resources})),running:running.map(t=>({id:t.id,owner:t.activity?.owner??t.owner,kind:t.activity?.kind??'worker'})),actions,independent}:undefined};
}
